---

# -----------------
# Control variables (Travis Settings)
# -----------------
#
# PUBLISH_IMAGES    Should be 'yes' to enable publishing to Docker Hub.
#
# If you set PUBLISH_IMAGES you must also set the following: -
#
# DOCKER_USERNAME
# DOCKER_PASSWORD

os: linux
services:
- docker

stages:
- name: publish latest
  if: |
    branch = master \
    AND env(PUBLISH_IMAGES) = yes
- name: publish tag
  if: |
    tag IS present \
    AND env(PUBLISH_IMAGES) = yes
- name: publish stable
  if: |
    tag IS present \
    AND tag =~ ^([0-9]+\.){1,2}[0-9]+$ \
    AND env(PUBLISH_IMAGES) = yes

env:
  global:
  - IMAGE_NAME=informaticsmatters/clubhouse-exporter

jobs:
  include:

  # Every successful master build results in a latest image
  # and every tag results in a tagged image.
  # Tags that match a RegEx are considered 'official' releases
  # and also result in a 'stable' image.

  - stage: publish latest
    name: Latest Container
    script:
    - docker build -t ${IMAGE_NAME}:latest .
    - if [ -n "$DOCKER_PASSWORD" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push ${IMAGE_NAME}:latest;
      fi

  - stage: publish tag
    name: Tagged Container
    script:
    - docker build -t ${IMAGE_NAME}:${TRAVIS_TAG} .
    - if [ -n "$DOCKER_PASSWORD" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push ${IMAGE_NAME}:${TRAVIS_TAG};
      fi

  - stage: publish stable
    name: Stable Container
    script:
    - if [ -n "$DOCKER_PASSWORD" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker pull ${IMAGE_NAME}:${TRAVIS_TAG};
        docker tag ${IMAGE_NAME}:${TRAVIS_TAG} ${IMAGE_NAME}:stable
        docker push ${IMAGE_NAME}:stable
      fi
